apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-user30
spec:
  applicationInstanceLabelKey: argocd.argoproj.io/argocd-userx
  dex:
    openShiftOAuth: true
  rbac:
    policy: g, cluster-admins, role:admin
    scopes: "[groups]"
  server:
    insecure: true
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
